### ISSUE TITLE
how to dynamic proxy  client ip and port

### ISSUE THREAD

**Issue by ywj1352** [Bernardo-MG/reactor-netty-proxy-example#11]
```
 private final void bridgeConnections(final Connection serverConn) {
        log.debug("Starting proxy client");

        // Connect to client, and react when connection becomes available
        client.connect()
            .subscribe((clientConn) -> {
                log.debug("Bridging connection with {}", bridge);

                bridge.bridge(serverConn, clientConn);
            });
    }
```
it get connection when `TcpServer.create().doOnConnection` but i want change proxy ip and pory when connection is opened.

i has same way. but it can't do dynamic proxy. Do you have any good ideas and opinions. thanks

**Comment by Bernardo-MG** [comment]
I'm not sure I understand the question. You want to set the target URL and port when opening the connection? In that case you have to start a new client each time a connection for the wrapped server is started.

Like this:

``` java
private final void bridgeConnections(final Connection serverConn) {
    final ReactorNettyProxyClient client;
    
    log.debug("Starting proxy client");

    // Start a new client to the proxy's target
    client = new ReactorNettyProxyClient(targetHost, targetPort);
    
    // Connect to client, and react when connection becomes available
    client.connect()
        .subscribe((clientConn) -> {
            log.debug("Bridging connection with {}", bridge);

            bridge.bridge(serverConn, clientConn);
        });
}
```

**Comment by ywj1352** [comment]
TcpClient --[TcpConnection1]--> TcpProxyServer --[TcpConnection2]-->ProxiedService

i want Without closing tcpconnection1, just change TcpConnection2 to TcpConnection3  in ReactorNetty.  Do you have  some good ideas about it？

**Comment by ywj1352** [comment]
> TcpClient --[TcpConnection1]--> TcpProxyServer --[TcpConnection2]-->ProxiedService
> 
> i want Without closing tcpconnection1, just change TcpConnection2 to TcpConnection3 in ReactorNetty. Do you have some good ideas about it？

-------------
i got it. if TcpConnection2 to TcpConnection3  change ,it just create a new TcpConnection1 . Thanks for your help
