### ISSUE TITLE
change bridge  method

### ISSUE THREAD

**Issue by ywj1352** [Bernardo-MG/reactor-netty-proxy-example#12]
maybe you can change 

`private Disposable bridge(final NettyInbound inbound, final NettyOutbound outbound) {
        Flux<byte[]> flux = inbound.receive().asByteArray();
        return flux.concatMap(next -> outbound.sendByteArray(Mono.just(next))).subscribe();
}`

to 

` private Disposable bridge(final NettyInbound inbound, final NettyOutbound outbound) {
        return outbound.send(inbound.receive().retain()).then().subscribe();
 }`

it can use netty zero-copy

**Comment by Bernardo-MG** [comment]
Thanks, I've applied the change and now it is much simpler an better.
